### ISSUE TITLE
Add support for default value for state dropdown also?

### ISSUE THREAD

**Issue by dheeraj-qasource-inhabitiq** [venkatmcajj/react-country-state-city#10]
Right now only country dropdown supports setting a default value, can we add the support for setting default value for the state dropdown also?

**Comment by venkatmcajj** [comment]
Once country selected then only state lists get updated based on the country, so if you have selected country already you can set default value for state also.

**Comment by dheeraj-qasource-inhabitiq** [comment]
> so if you have selected country already you can set default value for state also.

Could you please explain this a little more? I don't see the value prop on the `StateSelect` component

**Comment by venkatmcajj** [comment]
the props name is **defaultValue**
