### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by dheeraj-qasource-inhabitiq** [venkatmcajj/react-country-state-city#11]
The tgz zip file is missing in the directory that is required on this line to run the example
https://github.com/venkatmcajj/react-country-state-city/blob/master/example/package.json#L34

**Comment by venkatmcajj** [comment]
try npm i react-country-state-city from project directory then check

**Comment by dheeraj-qasource-inhabitiq** [comment]
Thank you!
