### ISSUE TITLE
Incorrect state codes?

### ISSUE THREAD

**Issue by dheeraj-qasource-inhabitiq** [venkatmcajj/react-country-state-city#19]
I was checking the states json file and noticed some state's code are numbers 
https://github.com/venkatmcajj/react-country-state-city/blob/master/data/statesminified.json#L507
Is this data correct?

example:
    "id": 4,
    "states": [
      {
        "id": 1118,
        "name": "Adrar",
        "state_code": "01"
      },
      {
        "id": 1119,
        "name": "Aïn Defla",
        "state_code": "44"
      },

**Comment by venkatmcajj** [comment]
These state codes are ISO codes without prefix **'DZ-'** not a phone code or zipcode.
