### ISSUE TITLE
Library has potential but multiple issues

### ISSUE THREAD

**Issue by replaysMike** [venkatmcajj/react-country-state-city#3]
Hi there,

Would love to utilize this library, but I've encountered a number of issues with it.

1. Flags aren't working
2. Can't pass props down to components (such as disabling autocomplete, and disabled properties to the input)
3. Scroll/scroll wheel isn't working on the state dropdown (but does on country?)
4. Reliance on bootstrap styles is less than ideal
5. Countries/states information should probably be in the build, not requested to an external server. Updates should come with new versions of the package

**Comment by venkatmcajj** [comment]
1 & 2  - Issue resolved and updated.
3. Check it from your side, npm was working fine.
4. We will update this in future.
5. Countries/states are not a static one, day by day states and cities are increasing if we want to update it means fetching data from external server would be easier or else need to give npm update for small small changes.
