### ISSUE TITLE
Unable to get countries & states

### ISSUE THREAD

**Issue by luantran1311** [venkatmcajj/react-country-state-city#8]
I'm using NextJS 14 with custom UI:

```
import {
    GetCountries,
    GetState
} from "react-country-state-city";
```

However in the useEffect, the GetCountries and GetState return nothing
![image](https://github.com/user-attachments/assets/32b3eb9f-edb7-45ae-ae86-19f284532a46)

  ```
  useEffect(() => {
      GetCountries().then((result : any) => {
        setCountriesList(result);
      });
  
      GetState().then((result : any) => {
        setStateList(result);
      });

      console.log(countriesList, stateList);
    }, []);
```

**Comment by venkatmcajj** [comment]
Records are coming but the way you consoled it was wrong. you are setting the values to state variables. try this one 

useEffect(() => {
    GetCountries().then((result : any) => {
      setCountriesList(result);
    });
    GetState().then((result : any) => {
      setStateList(result);
    });
  }, []);
useEffect(()=>{
    console.log(countriesList, stateList);
},[countriesList, stateList])
