### ISSUE TITLE
Could not find a declaration file for module 'react-country-state-city'.

### ISSUE THREAD

**Issue by dheeraj-qasource-inhabitiq** [venkatmcajj/react-country-state-city#9]
I am seeing this error after installing the package in my react-typescript project.\
I ran the `npm install --save react-country-state-city` command to install the package,

`Could not find a declaration file for module 'react-country-state-city'. '/node_modules/react-country-state-city/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-country-state-city` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-country-state-city';``

anyone know the fix for this issue?

**Comment by venkatmcajj** [comment]
Update to the latest version and then check.
